from simplex_dg.diagnostics.errors import (
    ErrorReport,
    error_report,
    l2_error,
    linf_error,
    relative_l2_error,
)
from simplex_dg.diagnostics.convergence import (
    ConvergenceRow,
    estimate_convergence_rates,
    format_convergence_table,
    rows_to_dicts_with_rates,
    write_convergence_csv,
)
from simplex_dg.diagnostics.leibniz import (
    LeibnizDefectRow,
    LeibnizDefects,
    LeibnizExperimentResult,
    attach_rates as attach_leibniz_rates,
    compute_leibniz_defect_component,
    compute_leibniz_defect_row,
    compute_leibniz_defects,
    discrete_energy,
    format_physical_table,
    format_reference_table,
    nodal_projection_matrix,
    observed_rate,
    project_nodal_samples,
    projection_closure_linf,
    rows_to_dicts as leibniz_rows_to_dicts,
    weighted_energy_residual,
    weighted_physical_l2_divided_by_j,
    weighted_reference_l2,
    write_csv as write_leibniz_csv,
)
from simplex_dg.diagnostics.projected_product import (
    ProjectedProductConvergenceRow,
    ProjectedProductResidualArrays,
    ProjectedProductResidualReport,
    attach_rates as attach_projected_product_rates,
    observed_rate as projected_product_observed_rate,
    projected_product_residual_arrays,
    projected_product_residual_report,
    rows_to_dicts as projected_product_rows_to_dicts,
    write_csv as write_projected_product_csv,
)

__all__ = [
    "ErrorReport",
    "l2_error",
    "relative_l2_error",
    "linf_error",
    "error_report",
    "ConvergenceRow",
    "estimate_convergence_rates",
    "rows_to_dicts_with_rates",
    "format_convergence_table",
    "write_convergence_csv",
    "LeibnizDefectRow",
    "LeibnizDefects",
    "LeibnizExperimentResult",
    "nodal_projection_matrix",
    "project_nodal_samples",
    "projection_closure_linf",
    "weighted_reference_l2",
    "weighted_physical_l2_divided_by_j",
    "weighted_energy_residual",
    "discrete_energy",
    "observed_rate",
    "compute_leibniz_defect_component",
    "compute_leibniz_defects",
    "compute_leibniz_defect_row",
    "attach_leibniz_rates",
    "leibniz_rows_to_dicts",
    "write_leibniz_csv",
    "format_reference_table",
    "format_physical_table",
    "ProjectedProductResidualArrays",
    "ProjectedProductResidualReport",
    "ProjectedProductConvergenceRow",
    "projected_product_residual_arrays",
    "projected_product_residual_report",
    "projected_product_observed_rate",
    "attach_projected_product_rates",
    "projected_product_rows_to_dicts",
    "write_projected_product_csv",
]
